#define CHASSIS_R2 9
#define CHASSIS_R1 1
#define MOGO_L1    5
#define MOGO_R1    4
#define ARM_L1     8
#define ARM_R1     3
#define BAR_M1     6
#define ROLL_M1    7
#define CHASSIS_L1 10
#define CHASSIS_L2 2